environment:
  global:
    PROJECT_NAME: music

  matrix:
      - TARGET: x86_64-pc-windows-msvc
        CHANNEL: stable
      - TARGET: x86_64-pc-windows-msvc
        CHANNEL: beta

# Based on https://github.com/japaric/rust-everywhere/blob/master/appveyor.yml
install:
  # Print Powershell version.
  - ps: $PSVersionTable.PSVersion
  - ps: pwd

  # Install Rust and Cargo
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

  # Install SDL2.
  - ps: Start-FileDownload https://www.libsdl.org/release/SDL2-devel-2.0.8-VC.zip -FileName sdl2.zip
  - ps: Expand-Archive sdl2.zip -DestinationPath sdl2
  - set LIB=%LIB%;C:\projects\music\sdl2\SDL2-2.0.8\lib\x64

  # Install SDL2_Mixer.
  - ps: Start-FileDownload https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.2-VC.zip -FileName sdl2_mixer.zip
  - ps: Expand-Archive sdl2_mixer.zip -DestinationPath sdl2_mixer
  - set LIB=%LIB%;C:\projects\music\sdl2_mixer\SDL2_mixer-2.0.2\lib\x64
  - ps: Get-ChildItem -Recurse -Depth 4

# 'cargo test' takes care of building for us, so disable Appveyor's build stage. This prevents
# the "directory does not contain a project or solution file" error.
# source: https://github.com/starkat99/appveyor-rust/blob/master/appveyor.yml#L113
build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo build --verbose
  - cargo build --verbose --example test
  - cargo build --example test-mp3
  - cargo build --example test-sdl-context
